swagger:
  contact:
    name: Giulliano Massarelli
    email: "giuliano.massarelli@geradordedevs.com.br"
  app:
    name: Notification API
    version: 0.0.1
    description: Challanger API to Studys
  base:
    package: br.com.geradordedevs.onlinebank

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path:
      path-mapping:
        health: /healthcheck

email:
  smpt-port: 584
  host-name: smtp.gmail.com
  user: gm.dev2022@gmail.com
  password: jgntapazcnvswuwe
  to: massarelli47@gmail.com
  from: gm.dev2002@gmail.com
  subject: Balanço anual - Gestão do mês

